name = "ive-malaysia-fanbase-website"
compatibility_date = "2024-01-01"
main = "workers-site/index.js"  # Satisfies legacy check

[build]
command = "npm run pages:build"

[site]
bucket = ".vercel/output/static"